### ISSUE TITLE
pennylane-qulacs with GPU (enhancement)

### ISSUE THREAD

**Issue by sassan72** [PennyLaneAI/pennylane-qulacs#32]
Qulacs can support GPU. Is it possible to run pennylane-qulacs with GPU?

**Comment by mlxd** [comment]
Hi @sassan72 , yes GPU support is available. The [install guide](https://github.com/PennyLaneAI/pennylane-qulacs#installation) gives details on how to install either the CPU or GPU versions of the plugin.
