### ISSUE TITLE
Rot gate

### ISSUE THREAD

**Issue by ycchen1989** [PennyLaneAI/pennylane-qulacs#8]
Hi,

I found that in this version, the 'Rot' gate has been removed, while in the old version, the 'Rot' gate was in _operations_map.
[https://github.com/soudy/pennylane-qulacs/blob/master/pennylane_qulacs/qulacs_device.py]

What is the reason of dropping this?

Thanks

**Comment by josh146** [comment]
Hi @ycchen1989! Qulacs doesn't natively support the `Rot` gate, so previously the plugin would decompose it into `RZ` and `RY` gates.

However, PennyLane now has built-in support for decomposing unsupported gates, so it should continue to work as before, even though `'Rot'` is not in the `_operations_map` 🙂

**Comment by dime10** [comment]
question answered
