### ISSUE TITLE
Unable to pip install pennylane-qulacs["gpu"]

### ISSUE THREAD

**Issue by Iaguigoiri** [PennyLaneAI/pennylane-qulacs#82]
Hi there,

At the moment I´m finding trouble installing the QLacs plugin to use the qlacs.simulator in a Quantum Long Short Term Memory Application. When I run the - **!pip install pennylane-qulacs["cpu"]**- it seems to work. 
  However when trying to run - **pip install qulacs pennylane-qulacs["gpu"]** -  in Google Colab, it keeps returning the following error:

 error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for qulacs-gpu (setup.py) ... error
  ERROR: Failed building wheel for qulacs-gpu
  Running setup.py clean for qulacs-gpu
Failed to build qulacs-gpu
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (qulacs-gpu)

My backend is setup as "qulacs.simulator" which also returns:

DeviceError: Device qlacs.simulator does not exist. Make sure the required plugin is installed.

**The versions used are:**
Pennylane QML: 0.39.0
Windows 10 Pro
Environment: Google Colab // Jupyter Notebook
Python: 3.10.12

**Comment by CatalinaAlbornoz** [comment]
Hi @Iaguigoiri, were you able to solve this issue? If so, what was the solution?
